name: "thesmiley's"
favicon: null
layout_spectrum: 0.91004
typography_spectrum: 0.6805899231694639
title: lifofsmiley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#75635f'
    - '#dcb193'
    - '#533126'
  brandStrength: 0.0625
  lightness: 0.8813388466369361
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
