name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.12561
typography_spectrum: 0
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#966624'
    - '#fff379'
    - '#e3b85a'
    - '#160807'
    - '#bbc7d3'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
