name: "dasmiley's"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84974
title: lifeofsmiley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbd0d3'
    - '#d90000'
    - '#eb6700'
    - '#fefefe'
    - '#d19988'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
