name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.3636
typography_spectrum: 0.48115
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020100'
    - '#fefffa'
    - '#686765'
    - '#77a06f'
    - '#de6f13'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
