name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9733865018934011
title: 'DEAN & ELISKA :)  lightofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ee8432'
    - '#fefc54'
    - '#5d1f0a'
    - '#b2b3ae'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
