layout_spectrum: 0.8159517114982009
typography_spectrum: 0.652914242586121
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.16158715751953423
  lightness: 0.3826066062320024
  saturation: 0.3022146231960505
  rhythmicContrast: 0.7769838797394186
name: 'dean & eliska :) lifeofsmiley'
favicon: null
title: 'DEAN & ELISKA :)  lightofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
