name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.07499
typography_spectrum: 0
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffa621'
    - '#fe4215'
    - '#0205fd'
    - '#097afd'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
