name: 'dean&eliska'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87172
title: 'DEAN&ELISKA:)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ee8432'
    - '#fefc54'
    - '#5d1f0a'
    - '#b2b3ae'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
