name: "thesmiley's"
favicon: null
layout_spectrum: 0.91004
typography_spectrum: 0.6805899231694639
title: lifofsmiley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b9b9b'
    - '#410100'
    - '#716664'
    - '#822111'
    - '#d6ccc3'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
