name: 'dean&eliska'
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'DEAN&ELISKA:)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3ded1'
    - '#ffffff'
    - '#d13a1f'
    - '#c9b17a'
    - '#d06755'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
