name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.4994
typography_spectrum: 0.48115
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#840000'
    - '#af6b00'
    - '#dcad00'
    - '#007268'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
