name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.07499
typography_spectrum: 0
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4a71a'
    - '#fefefe'
    - '#735d25'
    - '#4a1d11'
    - '#c80206'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
