name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.8784
typography_spectrum: 1
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d0d6'
    - '#ff2600'
    - '#003a00'
    - '#00939a'
    - '#8e8c73'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
