name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9733865018934011
title: 'DEAN & ELISKA :)  lightofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.8231399939395487
purpose: []
