layout_spectrum: 0.09077204344794154
typography_spectrum: 0.5073678235057741
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.6308607631362975
  lightness: 0.5341134793125093
  saturation: 0.05775191099382937
  rhythmicContrast: 0.1857682103291154
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: 'dean & eliska :) lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: art&design
    url: 'http://www.lagrandecache.com/'
    type: external
  - name: portfolio
    url: 'http://www.eliśkasmiley.com/'
    type: external
favicon: null
title: 'DEAN & ELISKA :)  lightofsmiley'
purpose: []
