name: 'dean&eliska'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84974
title: 'DEAN&ELISKA:)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3ded1'
    - '#ffffff'
    - '#d13a1f'
    - '#c9b17a'
    - '#d06755'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
