name: "thesmiley's"
favicon: null
layout_spectrum: 0.50805
typography_spectrum: 0.6805899231694639
title: lifeofsmiley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5d5351'
    - '#8d7c75'
    - '#d4c7bf'
  brandStrength: 0.4375
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
