name: 'dean&eliska'
favicon: null
layout_spectrum: 0.14838
typography_spectrum: 0.19474
title: 'DEAN&ELISKA:)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ee8432'
    - '#fefc54'
    - '#5d1f0a'
    - '#b2b3ae'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
