name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0.8784
typography_spectrum: 0.87172
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#3e403b'
    - '#bcab9b'
    - '#e37c5d'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
