name: 'dean & eliska :)'
favicon: null
layout_spectrum: 0.92969
typography_spectrum: 0.87172
title: 'DEAN & ELISKA :)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5d6de'
    - '#191919'
    - '#79acc9'
    - '#4285b0'
    - '#ad2b22'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
