name: 'dean&eliska'
favicon: null
layout_spectrum: 0.14316
typography_spectrum: 0.21638
title: 'DEAN&ELISKA:)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3ded1'
    - '#ffffff'
    - '#d13a1f'
    - '#c9b17a'
    - '#d06755'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
