name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b08'
    - '#37464b'
    - '#fefcfd'
    - '#b75b5b'
    - '#f182ac'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
