name: 'dean & eliska :) lifeofsmiley'
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'DEAN & ELISKA :)      lifeofsmiley'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee3dd'
    - '#632101'
    - '#70afb4'
    - '#f05b20'
    - '#ffa373'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
